# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Humblebee < Formula
  desc "Local-first CLI time tracking"
  homepage "https://www.timeandbill.de/en/humblebee/"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/grobmeier/humblebee/releases/download/v0.2.1/humblebee_0.2.1_darwin_amd64.tar.gz"
      sha256 "dcc6d65fc10d627225da99ae3ff0106ed089f35c6ad789f6f6f936f8395b36a8"

      define_method(:install) do
        bin.install "humblebee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/grobmeier/humblebee/releases/download/v0.2.1/humblebee_0.2.1_darwin_arm64.tar.gz"
      sha256 "591507cb8c938eebacc70436d43771440b26474b3412ab3eafd3f3122b93aaf9"

      define_method(:install) do
        bin.install "humblebee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/grobmeier/humblebee/releases/download/v0.2.1/humblebee_0.2.1_linux_amd64.tar.gz"
      sha256 "ae86fbbd44deda12f088fd7eb89126d8a09deb65b9678c2676b991db415f04e6"
      define_method(:install) do
        bin.install "humblebee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/grobmeier/humblebee/releases/download/v0.2.1/humblebee_0.2.1_linux_arm64.tar.gz"
      sha256 "3298938651bda8cc76e9cf6e9d97cb861cb7f0a3eeea2264e7449a0ec42e70ca"
      define_method(:install) do
        bin.install "humblebee"
      end
    end
  end
end
